name: zpevnik

publish_to: 'none'

version: 2.2.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jaguar_orm: any
  jaguar_query_sqflite: any
  sqflite: any
  path: any

  shared_preferences: any

  connectivity: any
  diacritic: any
  wakelock: any
    
  provider: any

  modal_bottom_sheet: any

  url_launcher: any
  flutter_share: any

  youtube_player_flutter: any
  flutter_svg: any
  flutter_reorderable_list: any

  firebase_analytics: any

  cupertino_icons: any

dev_dependencies:
  jaguar_orm_gen: any
  build_runner: any

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcon
      fonts:
      - asset: assets/fonts/CustomIcon.ttf

  assets:
    - assets/data.json
    - assets/images/
    - assets/images/songbooks/
