name: zpevnik

publish_to: 'none'

version: 3.0.5+127

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.2+1
  path: ^1.8.0

  objectbox: ^1.5.0
  objectbox_flutter_libs: any

  shared_preferences: ^2.0.6
  intl: ^0.17.0
  connectivity_plus: ^2.3.6
  diacritic: ^0.1.3
  wakelock: ^0.6.1+2

  provider: ^6.0.0

  modal_bottom_sheet: ^2.0.0

  url_launcher: ^6.0.6
  share_plus: ^4.0.3

  youtube_player_flutter: ^8.0.0
  just_audio: ^0.9.27

  flutter_cached_pdfview: ^0.4.1

  flutter_svg: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1

  adaptive_dialog: ^1.6.4

  flutter_speed_dial: ^6.0.0

  sign_in_with_apple: ^4.0.0

  uni_links: ^0.5.1

  device_info_plus: ^4.0.1

  # flutter_quill: ^5.0.4

  flutter_core_spotlight: ^1.0.4

  dotted_border: ^2.0.0+2

  font_awesome_flutter: ^10.1.0

  google_fonts: ^3.0.1

  cupertino_icons: ^1.0.3

  sentry_flutter: ^6.7.0

  package_info_plus: ^1.3.0
  web_socket_channel: ^2.2.0
  flutter_slidable: ^2.0.0
  firebase_core: ^1.23.0
  firebase_analytics: ^9.3.6

dev_dependencies:
  build_runner: ^2.0.4
  objectbox_generator: any

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

    - family: KaiseiHarunoUmi
      fonts:
        - asset: assets/fonts/KaiseiHarunoUmi-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

  assets:
    - assets/data.json
    - assets/images/
    - assets/images/logos/
    - assets/images/songbooks/
    - assets/

objectbox:
  output_dir: models