name: zpevnik

publish_to: 'none'

version: 3.1.0+138

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.2+1
  path: ^1.8.0

  objectbox: ^2.0.0
  objectbox_flutter_libs: any

  shared_preferences: ^2.0.6
  intl: ^0.18.0
  wakelock_plus: ^1.1.2

  url_launcher: ^6.0.6
  share_plus: ^7.1.0

  youtube_player_flutter: ^8.0.0
  just_audio: ^0.9.27

  flutter_cached_pdfview: ^0.4.1

  flutter_svg: ^2.0.6
  flutter_staggered_grid_view: ^0.7.0

  adaptive_dialog: ^1.9.0-no-macos.2

  dotted_border: ^2.0.0+2

  font_awesome_flutter: ^10.1.0

  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.3

  package_info_plus: ^4.1.0
  flutter_slidable: ^3.0.0
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  flat_buffers: ^2.0.5
  collection: ^1.16.0
  http: ^1.0.0
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  path_provider: ^2.0.15
  flutter_quill: ^8.1.6
  flex_color_picker: ^3.3.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.3.5
  sentry_flutter: ^7.12.0

dev_dependencies:
  build_runner: any
  objectbox_generator: any
  flutter_lints: any
  freezed: any
  json_serializable: any
  riverpod_generator: any

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

    - family: KaiseiHarunoUmi
      fonts:
        - asset: assets/fonts/KaiseiHarunoUmi-Regular.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/data.json
    - assets/images/
    - assets/images/logos/
    - assets/images/songbooks/
    - assets/

objectbox:
  output_dir: models