name: zpevnik

publish_to: 'none'

version: 2.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.1.7+2
  sqfentity: ^1.2.3
  sqfentity_gen: ^1.2.3
  path: ^1.8.0

  shared_preferences: ^2.0.5
  intl: ^0.17.0
  connectivity: ^3.0.3
  diacritic: ^0.1.3
  wakelock: ^0.5.1
    
  provider: ^5.0.0

  modal_bottom_sheet: ^2.0.0

  url_launcher: ^6.0.3
  flutter_share: ^2.0.0

  youtube_player_flutter: ^8.0.0
  flutter_svg: ^0.21.0+1
  flutter_reorderable_list: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0

  firebase_analytics: ^7.1.1

  uni_links: ^0.5.1

  flutter_nearby_connections: ^1.0.11
  device_info: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: any

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

  assets:
    - assets/data.json
    - assets/images/
    - assets/images/songbooks/
    - assets/
